#!/bin/bash
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

P4D_VERSION="22.2"

case ${MakeClean} in
	[Yy][Ee][Ss])
		if [ ! -f "helix-core-server.tgz" ]; then
			if [ "$ARCH" = "x86_64" ]; then
				P4D_URL="https://www.perforce.com/downloads/perforce/r${P4D_VERSION}/bin.linux26x86_64/helix-core-server.tgz"
			elif [ "$ARCH" = "i686" ]; then
				P4D_URL="https://www.perforce.com/downloads/perforce/r${P4D_VERSION}/bin.linux26x86/helix-core-server.tgz"
			else
				ERROR "Unsupported architecture."
				exit 1
			fi

			curl -L ${P4D_URL} -o helix-core-server.tgz -k
		fi
		tar -xvzf helix-core-server.tgz > /dev/null 2>&1 || true
		;;
esac
