#!/bin/sh

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

. /var/packages/$SYNOPKG_PKGNAME/scripts/pkg_utils

update_p4dctl_conf_file

exit 0
