#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### This script will be executed ONLY at package upgraded.
### Actions after package upgraded.
### ex. restore user settings.

. /var/packages/$SYNOPKG_PKGNAME/scripts/pkg_utils

update_p4dctl_conf_file

ShouldUpgradeDatabase=$UiInput_UpgradeDatabase

if [ "$ShouldUpgradeDatabase" = y \
    -o "$ShouldUpgradeDatabase" = Y \
    -o "$ShouldUpgradeDatabase" = yes \
    -o "$ShouldUpgradeDatabase" = true \
    -o "$ShouldUpgradeDatabase" = 0 ]; then

    if [ "$EUID" -eq 0 ]; then
        sudo -u Perforce $P4DCtlExecute upgrade -a
    else
        $P4DCtlExecute upgrade -a
    fi
fi

exit 0
