#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### This script will be executed ONLY at package upgraded.
### Actions after package upgraded.
### ex. restore user settings.

. /var/packages/${SYNOPKG_PKGNAME}/scripts/pkg_utils

ShouldUpgradeDatabase=$UiInput_UpgradeDatabase

if [ "$ShouldUpgradeDatabase" = y \
    -o "$ShouldUpgradeDatabase" = Y \
    -o "$ShouldUpgradeDatabase" = yes \
    -o "$ShouldUpgradeDatabase" = true \
    -o "$ShouldUpgradeDatabase" = 0 ]; then

    if [ -f "${HelixCoreServerConfigFile}" ]; then
        P4CASE=11
        export $(grep -v '^#' "${HelixCoreServerConfigFile}" | xargs -d '\n')

        stop_HelixCoreServer_service
        $P4DExecute -r "$P4ROOT" -C $P4CASE -L ../logs/log -J ../journals/journal -xu > /dev/null
    fi
fi

exit 0
