#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

. /var/packages/${SYNOPKG_PKGNAME}/scripts/pkg_utils

case $1 in
    start)
        start_HelixCoreServerCtl
        case "$?" in
            0) 
                exit 0
                ;;
            *) 
                exit 1
                ;;
        esac
        ;;
    stop)
        stop_HelixCoreServerCtl
        case "$?" in
            0)
                exit 0
                ;;
            *)
                exit 1
                ;;
        esac
        ;;
    status)
        status_HelixCoreServerCtl
        echo "$?"
        exit "$?"
        ;;
    killall)
        ;;
    log)
        exit 0
        ;;
esac

