#!/bin/sh

. /var/packages/$SYNOPKG_PKGNAME/scripts/pkg_utils

case $1 in
    start)
        start_P4Ctl
        case "$?" in
            0) 
                exit 0
                ;;
            *) 
                exit 1
                ;;
        esac
        ;;
    stop)
        stop_P4Ctl
        case "$?" in
            0)
                exit 0
                ;;
            *)
                exit 1
                ;;
        esac
        ;;
    status)
        status_P4Ctl
        echo "$?"
        exit "$?"
        ;;
    killall)
        ;;
    log)
        exit 0
        ;;
esac

