on:
  workflow_call:
    inputs:
      P4D_VERSION:
        required: true
        type: string
      DSM_VERSION:
        required: true
        type: string
      SPK_ARCH:
        required: true
        type: string
      CTL_ARCH:
        required: true
        type: string
      PackageBuildNumber:
        required: false
        type: number
        default: ${{ fromJSON(github.run_number) }}
      Beta:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build Package P4D=${{ inputs.P4D_VERSION }} DSM=${{ inputs.DSM_VERSION }} Arch=${{ inputs.SPK_ARCH }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: HelixCoreServerCtl-${{ inputs.CTL_ARCH }}
          path: out/HelixCoreServerCtl

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - run: pip install -r requirements.txt

      - id: build_package
        run: |
          python make.py \
            --platform-version ${{ inputs.DSM_VERSION }} \
            --arch ${{ inputs.SPK_ARCH }} \
            --p4d ${{ inputs.P4D_VERSION }} \
            ${{ (github.event_name != 'release' || (github.event_name == 'release' && github.event.release.prerelease) || inputs.Beta) && '--beta' || '' }} \
            --build-number ${{ inputs.PackageBuildNumber }} \
            --output P4Server.spk

      - name: Rename artifact
        run: |
          cp \
            P4Server.spk \
            ${{ runner.temp }}/P4Server-${{ steps.build_package.outputs.package_version }}-${{ inputs.SPK_ARCH }}-${{ inputs.DSM_VERSION }}.spk

      - name: Upload Package
        uses: actions/upload-artifact@v7
        with:
          name: P4Server-${{ steps.build_package.outputs.package_version }}-${{ inputs.SPK_ARCH }}-${{ inputs.DSM_VERSION }}
          path: ${{ runner.temp }}/P4Server-${{ steps.build_package.outputs.package_version }}-${{ inputs.SPK_ARCH }}-${{ inputs.DSM_VERSION }}.spk
          if-no-files-found: error
          archive: false
