name: Build & Release

on:
  workflow_dispatch:
  push:
  release:
    types: [published]

jobs:
  build-ctl:
    name: Build HelixCoreServerCtl
    strategy:
      fail-fast: false
      matrix:
        ARCH: ["x64"]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
        with:
          repository: FrozenStormInteractive/HelixCoreServerUtils
          ref: main

      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore src/HelixCoreServerCtl/HelixCoreServerCtl.csproj -r linux-${{ matrix.ARCH }}

      - name: Configure App paths
        run: |
          cat <<EOF > src/HelixCoreServerCtl/AppPaths.override.json
          {
              "ConfigFile": "/var/packages/HelixCoreServer/etc/p4dctl-ng.conf"
          }
          EOF         

      - name: Build Solution
        run: dotnet build src/HelixCoreServerCtl/HelixCoreServerCtl.csproj \
          --no-restore \
          -r linux-${{ matrix.ARCH }} \
          --self-contained

      - name: Publish
        run: |
          dotnet publish src/HelixCoreServerCtl/HelixCoreServerCtl.csproj \
          -o ${{ runner.temp }}/HelixCoreServerCtl \
          -r linux-${{ matrix.ARCH }} \
          --self-contained \
          -p:PublishReadyToRun=true \
          -c Release

      - id: upload_package
        name: Upload Package
        uses: actions/upload-artifact@v7
        with:
          name: HelixCoreServerCtl-${{ matrix.ARCH }}
          path: ${{ runner.temp }}/HelixCoreServerCtl
          if-no-files-found: error

  build-package:
    name: Build Package
    needs: build-ctl
    strategy:
      fail-fast: false
      matrix:
        P4D_VERSION: ["23.1", "23.2", "24.1", "24.2", "25.1", "25.2"]
        DSM_VERSION: ["7.1", "7.2", "7.3"]
        include:
          - SPK_PLATFORM: braswell
            SPK_ARCH: x86_64
            CTL_ARCH: x64
    uses: ./.github/workflows/build-package.yml
    with:
      P4D_VERSION: ${{ matrix.P4D_VERSION }}
      DSM_VERSION: ${{ matrix.DSM_VERSION }}
      SPK_PLATFORM: ${{ matrix.SPK_PLATFORM }}
      SPK_ARCH: ${{ matrix.SPK_ARCH }}
      CTL_ARCH: ${{ matrix.CTL_ARCH }}

  release:
    name: Upload Packages in Github Release
    needs: build-package
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: packages

      - name: Upload artifacts
        uses: softprops/action-gh-release@v3
        with:
          files: |
            packages/HelixCoreServer-*/HelixCoreServer-*.spk
