name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build Package
    strategy:
      fail-fast: false
      matrix:
        P4D_VERSION: ["22.2", "23.1", "23.2"]
        DSM_VERSION: ["7.1", "7.2"]
        include:
          - SPK_PLATFORM: braswell
            SPK_ARCH: x86_64
    uses: ./.github/workflows/build-package.yml
    with:
      P4D_VERSION: ${{ matrix.P4D_VERSION }}
      DSM_VERSION: ${{ matrix.DSM_VERSION }}
      SPK_PLATFORM: ${{ matrix.SPK_PLATFORM }}
      SPK_ARCH: ${{ matrix.SPK_ARCH }}

  release:
    name: Upload Packages in Github Release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: packages

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages/HelixCoreServer-*/HelixCoreServer-*.spk
