name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Perforce Helix Core Server Version (xx.x):'
        required: true
      packageVersion:
        description: 'Package Version (xxxx):'

jobs:
  build:
    name: Build Packages
    strategy:
      fail-fast: false
      matrix:
        include:
          - SPK_PLATFORM: braswell
            SPK_ARCH: x86_64
            DSM_VERSION: "7.1"
          - SPK_PLATFORM: evansport
            SPK_ARCH: i686
            DSM_VERSION: "7.1"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Toolchain
        run: |
          sudo -E ./.ci/setup-toolchain.sh
        env:
          SPK_PLATFORM: ${{ matrix.SPK_PLATFORM }}
          DSM_VERSION: ${{ matrix.DSM_VERSION }}

      - name: Build Package
        run: |
          sudo -E ./.ci/build-package.sh
        env:
          SPK_PLATFORM: ${{ matrix.SPK_PLATFORM }}
          SPK_ARCH: ${{ matrix.SPK_ARCH }}
          DSM_VERSION: ${{ matrix.DSM_VERSION }}
          SPK_PACKAGE_VERSION: ${{ github.event.inputs.version }}
